%% visualizeMatField usage examples
% Run one section at a time (Ctrl+Enter in the MATLAB Editor).

%% 1. Required MAT file and variable, all other options use defaults
% Volume mode. Use the in-window dropdown to switch modes.
matFile = fullfile(fileparts(mfilename('fullpath')), ...
    'Data', 'data_uniGrid_zFlowDirct.mat');
visualizeMatField(matFile, 'rho.rho_XYZ');

%% 2. Precisely specified slice
% 'figure' is accepted as an alias of 'slice'. The dimension accepts
% 1/2/3, I/J/K, or X/Y/Z.
% visualizeMatField(matFile, 'T.T_XYZ', ...
%     'PlotType', 'slice', 'Dimension', 'Z', 'Index', 80);

%% 3. Interactive slice with an initially selected dimension
% Dimension is fixed by the command line; index defaults to the center and
% remains editable in the figure.
% visualizeMatField(matFile, 'GD.gradNorm_XYZ', ...
%     'PlotType', 'slice', 'Dimension', 1);

%% 4. Three-dimensional multi-isosurface view
% visualizeMatField(matFile, 'rho.rho_XYZ', 'PlotType', 'volume');

%% 5. Tuned three-dimensional view
% visualizeMatField(matFile, 'T.gradNorm_XYZ', 'PlotType', '3d', ...
%     'NumIsosurfaces', 7, ...
%     'IsoRange', [0.10, 0.70], ...
%     'SurfaceAlpha', 0.16, ...
%     'MaxRenderSize', 110);

%% 6. Exact isosurface levels (no level controls are added to the figure)
% visualizeMatField(matFile, 'rho.rho_XYZ', 'PlotType', 'volume', ...
%     'IsoValues', [0.35, 0.60, 0.85], ...
%     'SurfaceAlpha', 0.20);

%% 7. Complete canonical syntax and another MAT file
% visualizeMatField('D:\data\another_file.mat', 'n.gradX_XYZ', ...
%     'PlotType', 'slice', ...
%     'Dimension', 'Y', ...
%     'Index', 60, ...
%     'ColorLimits', 'slice', ...
%     'Colormap', 'parula');
