% Optional cross-language fixture, generated by MATLAB itself rather than a Python writer.
% Run from the python directory: run('tests/generate_matlab_fixture.m')
outputFolder = fullfile(fileparts(mfilename('fullpath')), 'generated');
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end
[dim1, dim2, dim3] = ndgrid(0:3, 0:5, 0:7);
flow.field = single(100 * dim1 + 10 * dim2 + dim3);
flow.plane = flow.field(:, :, 1);
flow.nested.matrix = uint16(reshape(1:24, [4, 6]));
flow.logical = flow.field > 1;
flow.complex = complex(flow.field, ones(size(flow.field), 'single'));
ignoredVector = 1:10;
save(fullfile(outputFolder, 'native_v7.mat'), 'flow', 'ignoredVector', '-v7');
save(fullfile(outputFolder, 'native_v73.mat'), 'flow', 'ignoredVector', '-v7.3');
fprintf('NATIVE_MAT_FIXTURES_OK\n');
